import { ViewCourseType } from "@/types/course-settings";
import { LeaderboardType } from "@/types/leaderboard";
import john from "@/assets/john.png";
import abigail from "@/assets/abigail.png";

export const ongoingCoursesData: ViewCourseType[] = [
  {
    id: 1,
    student: "John Doe",
    email: "john.doe@example.com",
    userId: "JD123",
    dateStarted: "2024-01-10",
    status: "Active",
  },
  {
    id: 2,
    student: "Jane Smith",
    email: "jane.smith@example.com",
    userId: "JS456",
    dateStarted: "2024-02-14",
    status: "inactive",
  },
  {
    id: 3,
    student: "Michael Johnson",
    email: "michael.johnson@example.com",
    userId: "MJ789",
    dateStarted: "2024-03-12",
    status: "Active",
  },
  {
    id: 4,
    student: "Emily Davis",
    email: "emily.davis@example.com",
    userId: "ED012",
    dateStarted: "2024-04-20",
    status: "Active",
  },
  {
    id: 5,
    student: "Daniel Brown",
    email: "daniel.brown@example.com",
    userId: "DB345",
    dateStarted: "2024-05-05",
    status: "inactive",
  },
];

export const finishedCoursesData: ViewCourseType[] = [
  {
    id: 1,
    student: "John Doe",
    email: "john.doe@example.com",
    userId: "JD123",
    dateStarted: "2024-01-10",
    finishedDate: "2024-03-15",
    status: "active",
  },
  {
    id: 2,
    student: "Jane Smith",
    email: "jane.smith@example.com",
    userId: "JS456",
    dateStarted: "2024-02-14",
    finishedDate: "2024-05-18",
    status: "inactive",
  },
  {
    id: 3,
    student: "Michael Johnson",
    email: "michael.johnson@example.com",
    userId: "MJ789",
    dateStarted: "2024-03-12",
    finishedDate: "2024-06-25",
    status: "active",
  },
  {
    id: 4,
    student: "Emily Davis",
    email: "emily.davis@example.com",
    userId: "ED012",
    dateStarted: "2024-04-20",
    finishedDate: "2024-07-30",
    status: "inactive",
  },
  {
    id: 5,
    student: "Daniel Brown",
    email: "daniel.brown@example.com",
    userId: "DB345",
    dateStarted: "2024-05-05",
    finishedDate: "2024-08-10",
    status: "active",
  },
];

export const unfinishedCoursesData: ViewCourseType[] = [
  {
    id: 1,
    student: "John Doe",
    email: "john.doe@example.com",
    userId: "JD123",
    dateStarted: "2024-01-10",
    lastTaken: "2024-03-15",
    status: "active",
  },
  {
    id: 2,
    student: "Jane Smith",
    email: "jane.smith@example.com",
    userId: "JS456",
    dateStarted: "2024-02-14",
    lastTaken: "2024-05-18",
    status: "inactive",
  },
  {
    id: 3,
    student: "Michael Johnson",
    email: "michael.johnson@example.com",
    userId: "MJ789",
    dateStarted: "2024-03-12",
    lastTaken: "2024-06-25",
    status: "active",
  },
  {
    id: 4,
    student: "Emily Davis",
    email: "emily.davis@example.com",
    userId: "ED012",
    dateStarted: "2024-04-20",
    lastTaken: "2024-07-30",
    status: "inactive",
  },
  {
    id: 5,
    student: "Daniel Brown",
    email: "daniel.brown@example.com",
    userId: "DB345",
    dateStarted: "2024-05-05",
    lastTaken: "2024-08-10",
    status: "active",
  },
];

export const sapphireLeaderboardData: LeaderboardType[] = [
  {
    id: 1,
    rank: 1,
    avatar: john,
    handle: "@johndoe",
    position: 1,
    score: 250,
  },
  {
    id: 2,
    rank: 2,
    avatar: abigail,
    handle: "@abigail",
    position: 2,
    score: 1050,
  },
  {
    id: 3,
    rank: 3,
    avatar: john,
    handle: "@johndoe",
    position: 3,
    score: 990,
  },
  {
    id: 4,
    rank: 4,
    avatar: john,
    handle: "@johndoe",
    position: 4,
    score: 980,
  },
  {
    id: 5,
    rank: 5,
    avatar: john,
    handle: "@johndoe",
    position: 5,
    score: 740,
  },
];
export const mockExamLeaderboardData: LeaderboardType[] = [
  {
    id: 1,
    rank: 1,
    avatar: john,
    handle: "@johndoe",
    position: 1,
    percentage: 50,
  },
  {
    id: 2,
    rank: 2,
    avatar: abigail,
    handle: "@abigail",
    position: 2,
    percentage: 40,
  },
  {
    id: 3,
    rank: 3,
    avatar: john,
    handle: "@johndoe",
    position: 3,
    percentage: 20,
  },
  {
    id: 4,
    rank: 4,
    avatar: john,
    handle: "@johndoe",
    position: 4,
    percentage: 70,
  },
  {
    id: 5,
    rank: 5,
    avatar: john,
    handle: "@johndoe",
    position: 5,
    percentage: 95,
  },
];

export const cardDetails = [
  {
    title: "Total Time Spent",
    subTitle: "Total no. of customers",
    value: "0.00.00",
    color: "text-violet1",
    bg: "bg-violet3",
  },
  {
    title: "Overall Progress",
    subTitle: "No. of active customers",
    value: 0,
    color: "text-pink1",
    bg: "bg-pink2",
  },
  {
    title: "Avg assessment Score",
    subTitle: "No. of inactive customers",
    value: 0,
    color: "text-orange1",
    bg: "bg-orange4",
  },
];

export const dashboardStudentsData = [
  {
    id: 1,
    name: "Denilson Igwe",
    email: "denilson.igwe@example.com",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    dateJoined: "12/03/23",
    userId: "ED25J",
    examChoice: "Jamb",
    userLocation: "Lagos",
    examDate: "12/10/23",
    status: "active",
  },
  {
    id: 2,
    name: "Alex Brown",
    email: "alex.brown@example.com",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    dateJoined: "01/01/23",
    userId: "XT74K",
    examChoice: "WAEC",
    userLocation: "Abuja",
    examDate: "15/10/23",
    status: "inactive",
  },
  {
    id: 3,
    name: "Maria Smith",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    dateJoined: "10/06/22",
    userId: "GH94B",
    examChoice: "Jamb",
    userLocation: "Enugu",
    examDate: "18/10/23",
    status: "active",
  },
  {
    id: 4,
    name: "John Doe",
    email: "john.doe@example.com",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    dateJoined: "15/05/23",
    userId: "DE98P",
    examChoice: "Neco",
    userLocation: "Port Harcourt",
    examDate: "20/10/23",
    status: "active",
  },
  {
    id: 5,
    name: "Alice Johnson",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    dateJoined: "22/07/23",
    userId: "PO34T",
    examChoice: "Jamb",
    userLocation: "Kano",
    examDate: "23/10/23",
    status: "active",
  },
  {
    id: 6,
    name: "Michael Lee",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    dateJoined: "03/02/23",
    userId: "OI87H",
    examChoice: "WAEC",
    userLocation: "Jos",
    examDate: "25/10/23",
    status: "active",
  },
  {
    id: 7,
    name: "Sara O'Connor",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    dateJoined: "05/09/22",
    userId: "PK12Q",
    examChoice: "Jamb",
    userLocation: "Owerri",
    examDate: "27/10/23",
    status: "active",
  },
  {
    id: 8,
    name: "David Silva",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    dateJoined: "18/11/23",
    userId: "LI45Z",
    examChoice: "Neco",
    userLocation: "Lagos",
    examDate: "29/10/23",
    status: "inactive",
  },
  {
    id: 9,
    name: "Jessica Wright",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    dateJoined: "20/12/23",
    userId: "WS78D",
    examChoice: "Jamb",
    userLocation: "Ibadan",
    examDate: "02/11/23",
    status: "active",
  },
  {
    id: 10,
    name: "Chris Green",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    dateJoined: "22/01/23",
    userId: "YU34M",
    examChoice: "WAEC",
    userLocation: "Ilorin",
    examDate: "05/11/23",
    status: "inactive",
  },
  {
    id: 11,
    name: "Sophia Turner",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    dateJoined: "25/02/23",
    userId: "FR89L",
    examChoice: "Neco",
    userLocation: "Uyo",
    examDate: "07/11/23",
    status: "active",
  },
  {
    id: 12,
    name: "Isaac Newton",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    dateJoined: "28/03/23",
    userId: "MN56J",
    examChoice: "Jamb",
    userLocation: "Abeokuta",
    examDate: "09/11/23",
    status: "active",
  },
  {
    id: 13,
    name: "Grace Hopper",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    dateJoined: "30/04/23",
    userId: "LK67R",
    examChoice: "Neco",
    userLocation: "Benin",
    examDate: "11/11/23",
    status: "active",
  },
  {
    id: 14,
    name: "James Cameron",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    dateJoined: "05/06/23",
    userId: "CV23U",
    examChoice: "WAEC",
    userLocation: "Asaba",
    examDate: "14/11/23",
    status: "active",
  },
  {
    id: 15,
    name: "Emily Stone",
    email: "maria.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    dateJoined: "12/07/23",
    userId: "QW45Y",
    examChoice: "Jamb",
    userLocation: "Warri",
    examDate: "16/11/23",
    status: "active",
  },
];
